name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment (tagged release)
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        GO_VERSION=${TAG_NAME#v}
        echo "GO_VERSION=$GO_VERSION" >> $GITHUB_ENV
    
    - name: Set up environment (non-tagged release)
      if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
      run: |
          GO_VERSION=latest
          echo "GO_VERSION=$GO_VERSION" >> $GITHUB_ENV
 
    - name: Build
      run: make build